#Automatically generated by pip2arch on 2015-06-27

pkgname=python-unicodemoticon
pkgver=1.0.6
pkgrel=1
pkgdesc="Like a Color Picker but for Unicode Emoticons. Trayicon with Unicode Emoticons using Python3 Qt5."
url="https://github.com/juancarlospaco/unicodemoticon"
depends=('python' 'pip' 'python-pyqt5')
optdepends=('ttf-symbola: Font with emoji')
makedepends=('python-distribute')
license=('GPL')
arch=('any')
source=('https://pypi.python.org/packages/source/u/unicodemoticon/unicodemoticon-1.0.6.zip')
md5sums=('781f8af6d1b07e8a97c29aaacb8514ce')

build() {
    cd $srcdir/unicodemoticon-1.0.6
    python setup.py build
}

package() {
    cd $srcdir/unicodemoticon-1.0.6
    python setup.py install --root="$pkgdir" --optimize=1 
}
