#Automatically generated by pip2arch on 2015-05-17

pkgname=python-unicodemoticon
pkgver=1.0.0
pkgrel=1
pkgdesc="Like a Color Picker but for Unicode Emoticons. Trayicon with Unicode Emoticons using Python3 Qt5."
url="https://github.com/juancarlospaco/unicodemoticon"
depends=('python' 'pip')
makedepends=('python3' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/source/u/unicodemoticon/unicodemoticon-1.0.0.zip')
md5sums=('44c427725da64bdefea051b3c62e0ede')

build() {
    cd $srcdir/unicodemoticon-1.0.0
    python setup.py build
}

package() {
    cd $srcdir/unicodemoticon-1.0.0
    python setup.py install --root="$pkgdir" --optimize=1 
}
